from pathlib import Path
path = Path('/home/damien/.openclaw/workspace/openclaw-mission-control/src/features/agents/views/hierarchy/HierarchyCanvas.tsx')
data = path.read_text()
data = data.replace('className="relative h-0 flex-1 overflow-hidden border-t"', 'className="relative flex-1 min-h-0 overflow-hidden border-t"', 1)
data = data.replace('className="flex flex-wrap items-start gap-2 border-b px-4 py-2"', 'className="flex flex-wrap items-center gap-1.5 border-b px-3 py-1.5"', 1)
data = data.replace('className="flex-1 overflow-auto px-4 pb-3 pt-2"', 'className="flex-1 overflow-auto px-3 pb-2.5 pt-1.5"', 1)
data = data.replace('className="mx-auto max-w-[1100px]"', 'className="mx-auto max-w-4xl"', 1)
data = data.replace('className="mx-auto mt-4 h-3 w-px bg-gradient-to-b from-transparent via-[var(--agents-panel-border)] to-transparent"', 'className="mx-auto mt-2 h-2 w-[2px] bg-gradient-to-b from-transparent via-[var(--agents-panel-border)] to-transparent"', 1)
data = data.replace('className="mt-1 grid gap-2 lg:grid-cols-2 xl:grid-cols-3" style={{ gridAutoRows: "1fr" }}', 'className="mt-1 grid gap-1.5 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3" style={{ gridAutoRows: "minmax(0, auto)" }}', 1)
data = data.replace('className="relative flex h-full flex-col rounded-[28px] border"', 'className="relative flex h-full flex-col rounded-2xl border"', 1)
data = data.replace('className="flex items-start justify-between border-b px-4 py-3"', 'className="flex items-center justify-between border-b px-3 py-2"', 1)
data = data.replace('className="flex-1 space-y-2 px-3 py-3"', 'className="flex-1 space-y-1.5 px-3 py-2.5"', 1)
data = data.replace('className="flex items-start gap-1 rounded-full px-3 py-1 text-xs font-medium transition-colors"', 'className="flex items-center gap-1 rounded-full px-2.5 py-0.75 text-[10px] font-medium transition-colors"', 1)
path.write_text(data)
